name: trauma
description: "A new Flutter project for managing trauma cases and hospital emergencies."
publish_to: 'none'  # Keep this line if you don't want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # Firebase dependencies
  firebase_core: ^3.8.0  # Inicializa Firebase en tu app
  firebase_auth: ^5.3.3  # Manejo de autenticaci√≥n
  cloud_firestore: ^5.5.0  # Base de datos en la nube

  # Add essential dependencies for animations and icons
  cupertino_icons: ^1.0.8
  flutter_animate: ^4.2.0  # For animations
  provider: ^6.0.3  # For state management

  # Additional dependencies for UI components
  cached_network_image: ^3.2.1  # For caching images
  flutter_localizations:
    sdk: flutter  # For localization support

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logoMelipilla.png
    - assets/infra.png
    - assets/medico.png
    - assets/atencion.png
